### ISSUE TITLE
DPO Enhancements v1

### ISSUE THREAD

**Issue by euroblaze** [euroblaze/dpo#1]
- (1) Provide Name of Category as a title of the table.
- (2) Show signature line based on selection under `PrintOptions` tab (5).
- Weight if specified on product * quantity, else empty.
- Volume if specified on product * quantity, else empty.
- (6) Offer a list of categories (subcategories indented), products from which, customer has to sign on delivery note upon receipt.
- (7) Align columns
- (8) Use same document header as in QPO and IPO.

![image](https://github.com/euroblaze/dpo/assets/7826363/2cd5e1d4-eac8-40e7-9b30-1c263792707a)
![image](https://github.com/euroblaze/dpo/assets/7826363/e8c0647f-afef-472c-8bc7-d10200910e9f)

**Comment by holengocquy** [comment]
@euroblaze what if we print the slip when the transfer's status is done?

**Comment by euroblaze** [comment]
@holengocquy 
Then the `delivered quantities` will be updated to reflect the same.
The `done` status is set by the warehouse-manager when he hands out the goods to the worker going onsite.
Does that sound right?

**Comment by holengocquy** [comment]
Yeah, it's fine. But do we still need to print Signature (required) when it's done?

**Comment by euroblaze** [comment]
Yea of course.

Done means stock left warehouse.
Signed means stock was received by customer.

**Comment by euroblaze** [comment]
@holengocquy 
At about the position (8), print the contents of the _Note_ tab.
