### ISSUE TITLE
Serial Numbers and other Data

### ISSUE THREAD

**Issue by euroblaze** [euroblaze/dpo#2]
- True/false PrintOption to print serial numbers (and other data fields) in last page.

> Best idea seems to be to relocate this code to the dpo module, because this PDF maybe generated for deliveries which are _not related to a project at all.

> Generally speaking, the PDFs of delivery-notes should be independent to Projects module.

![2023-09-13_13-13-57](https://github.com/euroblaze/dpo/assets/7826363/0d011179-0c26-449b-9dec-b208e1c3c279)

**Comment by holengocquy** [comment]
This is using product_type_id which comes from poweron_product (enerix_product on demo). This feature'd make DPO depending to poweron_product.

**Comment by holengocquy** [comment]
Another point, there's gap of code between demo & main of poweron repo. In the report that prints serial number, it uses **product_url** which doesn't present in main. Shall we keep this field in the report?

**Comment by euroblaze** [comment]
On Thu 14. Sep 2023 at 11:23, 'holengocquy' via euroblaze Github Common
Account ***@***.***> wrote:

> Another point, there's gap of code between demo & main of poweron repo. In
> the report that prints serial number, it uses *product_url* which doesn't
> present in main. Shall we keep this field in the report?
>
Not sure.
Let’s discuss the implications on call.

>
