### ISSUE TITLE
Logo, Logo Position

### ISSUE THREAD

**Issue by euroblaze** [euroblaze/dpo#3]
- Print Logo checkbox and the Logo Position settings seem not to reflect on PDF.

**Comment by holengocquy** [comment]
there's a conflict with ipo and qpo where they inherited to the same header. I realized that yesterday and am currently thinking of having a generic technical solution

**Comment by euroblaze** [comment]
There’s no customer value in providing this choice.
This is just a piece of paper for the warehouse.
Look and feel not important (though must be consistent).

So completely skip this setting and fix the logo on the left side. Then
close the issue!

Thanks
